import { AudioPlayerVolumeControl } from '../Types';

export default {
  classNames: {
    'sr-only': ['sr-only'],
    tracklist: ['btn', 'btn-tracklist'],
    'previous-audio': ['btn', 'btn-previous-audio'],
    backward: ['btn', 'btn-backward'],
    play: ['btn', 'btn-play'],
    reset: ['btn', 'btn-reset'],
    forward: ['btn', 'btn-forward'],
    'next-audio': ['btn', 'btn-next-audio'],
    'closed-captioning': ['btn', 'btn-closed-captioning'],
    mute: ['btn', 'btn-mute'],
  },
  icons: {
    tracklist__false: ['fa', 'fa-list-ol'],
    tracklist__true: ['fa', 'fa-window-close'],
    'previous-audio': ['fa', 'fa-step-backward'],
    backward: ['fa', 'fa-backward'],
    play__false: ['fa', 'fa-play'],
    play__true: ['fa', 'fa-pause'],
    reset: ['fa', 'fa-undo'],
    forward: ['fa', 'fa-forward'],
    'next-audio': ['fa', 'fa-step-forward'],
    'closed-captioning__false': ['fa', 'fa-closed-captioning'],
    'closed-captioning__true': ['fa', 'fa-window-close'],
    mute__false: ['fa', 'fa-volume-up'],
    mute__true: ['fa', 'fa-volume-off'],
  },
  iconElements: {
    tracklist__false: null,
    tracklist__true: null,
    'previous-audio': null,
    backward: null,
    play__false: null,
    play__true: null,
    reset: null,
    forward: null,
    'next-audio': null,
    'closed-captioning__false': null,
    'closed-captioning__true': null,
    mute__false: null,
    mute__true: null,
  },
  useHoursInTimestamps: true,
  features: {
    showTracklist: true,
    showTrackNav: true,
    volumeControl: 'mute' as AudioPlayerVolumeControl,
    showFastForward: true,
    showRewind: true,
    showClosedCaptioning: true,
  },
};
